### PR TITLE
Cleaned up tests.  Trying it out a little differently

### PR DESCRIPTION
**Pull request by SerenadeX**

### CODE REVIEW

**Comment by SerenadeX** [comment]
Let me know if you think these tests are sufficient

**Comment by aaronbarker** [comment]
Pulled the testing branch down and went to the test folder. The page comes up but has a bunch of JS errors like jQuery missing. Am I looking in the wrong spot?

**Comment by aaronbarker** [comment]
But to your main question, it looks like the tests are sufficient.  The other issue we had was making sure complete callback was run, but I guess that is inherently confirmed in each test currently.

**Comment by SerenadeX** [comment]
yeah you just have to run `npm install` and then `npm test`  Then it runs through the tests

**Comment by aaronbarker** [comment]
Are server side tests the right way to go here?  You wouldn't be able to test in browsers for if there were issues with IE (cause it NEVER has problems =P). It also doesn't take into account latency issues since it is loading the scripts essentially instantaneously instead of race conditions happening.  Which makes me think of other tests like having a script load slowly somehow and making sure they are executed in order (even when loaded out of order due to a slow load).

**Comment by SerenadeX** [comment]
They are not server side tests.  They are browser tests.  If you look at karma.conf.js, it has a list of browsers it can test in.  I can add other ones if we need to.  It opens up the browser and runs this stuff in it.

**Comment by SerenadeX** [comment]
As for the latency issues I'm not sure how to solve that with a test, but it loads it in order.  It creates a stack and loads each one at a time and doesn't move on to the next until an onreadystate fires.  I'm not sure how to write a test for that but yeah.

**Comment by SerenadeX** [comment]
Ok check out the README to see how to run the tests on your local machine.

**Comment by SerenadeX** [comment]
Abandoning project

**Pull request closed without merging**
